services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "li-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      - base

  backend:
    container_name: tiny-url-backend
    build: .
    depends_on:
      - postgres
    env_file:
      - prod.env
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/src/server.js"
    restart: unless-stopped
    networks:
      - base

  backend-proxy:
    image: nginx:stable-alpine
    container_name: backend-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - base

  frontend:
    build: ../tiny-url-front
    ports:
      - "8080:80"
    env_file:
      - ../tiny-url-front/.env.production
    restart: unless-stopped
    networks:
      - base

volumes:
  db-data:
  pgadmin-data:

networks:
  base:
    driver: bridge
